### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by ghost** [hashicorp/da-connect-demo#1]
Thanks for putting this up. Its really useful.

I am wondering what happens when the consul in each data center goes down and up and its IP address changes. How do he other consuls find it ?

**Comment by anubhavmishra** [comment]
@gedw99 the Consul agents are using a [Gossip](https://www.consul.io/docs/internals/gossip.html) protocol when we communicate with each other. This takes care of things like failure detection (when agents go offline and come online with a different IP etc). When an agent comes back online with a new IP, it just needs to advertise it to the cluster and the rest is taken care by Gossip. 

Let me know if that helps? I am going to close this issue. If you still have questions, feel free to reopen the issue.

**Comment by ghost** [comment]
Thanks for the heads-up !
